branch_whitelist = []
disable_bump_commit = true
disable_changelog = true
from_latest_tag = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
ignore_fixup_commits = true
ignore_merge_commits = false
post_bump_hooks = []
post_package_bump_hooks = []
pre = "alpha.*"
pre_bump_hooks = []
pre_package_bump_hooks = []
scopes = [
  "acme",
  "bewcloud",
  "caddy",
  "cocogitto",
  "cog",
  "copier",
  "cspell",
  "devshell",
  "disko",
  "domain",
  "features",
  "flake",
  "git",
  "github",
  "homepage-dashboard",
  "hosts",
  "hosts/home-lab",
  "hosts/test-bed",
  "jscpd",
  "justfile",
  "megalinter",
  "nginx",
  "nix-cmds",
  "packages",
  "pangolin",
  "peertube",
  "pgadmin",
  "pre-commit",
  "radicale",
  "rclone",
  "revert",
  "scalpel",
  "secrets",
  "services",
  "shell",
  "sops",
  "variables",
  "vscode",
  "zed"
]
skip_ci = "[skip ci]"
skip_untracked = false

[bump_profiles]

[changelog]
authors = []
path = "CHANGELOG.md"

[commit_types]

[git_hooks]

[packages]
